---
- name: Add DotDeb key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg

- name: Add DotDeb repository
  apt_repository: repo='{{ item }}'
  with_items:
    - deb http://packages.dotdeb.org jessie all
    - deb-src http://packages.dotdeb.org jessie all
