---
- name: Install PHP FPM
  apt: pkg=php7.0-fpm state=latest update_cache=yes cache_valid_time=3600

- name: Install PHP packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: "{{php_packages}}"

- name: Remove default pool
  file: path=/etc/php/7.0/fpm/pool.d/www.conf state=absent
  notify: restart php7-fpm

#- name: Apply PHP FPM settings
#  template: src=php.ini dest=/etc/php/7.0/fpm/php.ini owner=root group=root mode=0644

- name: Install pools
  template: src=templates/fpm-pools/{{ item.src }} dest=/etc/php/7.0/fpm/pool.d/{{ item.dest }}
  notify: restart php7-fpm
  with_items: "{{php_fpm_pools}}"

- include: xdebug.yml
  when: php_xdebug
