---
- name: Install PHP FPM
  apt: pkg=php7.0-fpm state=latest update_cache=yes cache_valid_time=3600

- name: Install PHP packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: "{{php_packages}}"

- name: Ensure Xdebug not present
  apt: pkg=php7.0-xdebug state=absent update_cache=yes cache_valid_time=3600
  notify: restart php7-fpm

- name: Remove default pool
  file: path=/etc/php/7.0/fpm/pool.d/www.conf state=absent
  notify: restart php7-fpm

- name: Install pools
  template: src=templates/fpm-pools/{{ item.src }} dest=/etc/php/7.0/fpm/pool.d/{{ item.dest }}
  notify: restart php7-fpm
  with_items: "{{php_fpm_pools}}"
