#! /usr/bin/env php
<?php

function factorial($number) {
    if ($number == 1) {
        return $number;
    }

    return $number * factorial($number - 1);
}

$number = factorial(6);

echo "{$number}\n";
